package B.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class BIdentifier_Constraints extends BaseConstraintsDescriptor {
  public BIdentifier_Constraints() {
    super(CONCEPTS.BIdentifier$nT);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BIdentifier$nT = MetaAdapterFactory.getConcept(0x17157e91c2e440eaL, 0xaefc3d3bbdd08639L, 0x7d382cf97c756979L, "B.structure.BIdentifier");
  }
}
