package Solidity.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myMappingElement__BehaviorDescriptor = new MappingElement__BehaviorDescriptor();
  private final BHDescriptor myPayableFunctionDefinition__BehaviorDescriptor = new PayableFunctionDefinition__BehaviorDescriptor();
  private final BHDescriptor myStateVariableDeclaration__BehaviorDescriptor = new StateVariableDeclaration__BehaviorDescriptor();
  private final BHDescriptor myFunctionDefinition__BehaviorDescriptor = new FunctionDefinition__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myFunctionDefinition__BehaviorDescriptor;
      case 1:
        return myMappingElement__BehaviorDescriptor;
      case 2:
        return myPayableFunctionDefinition__BehaviorDescriptor;
      case 3:
        return myStateVariableDeclaration__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xf72d32028a4541adL, 0xbb612369f7191040L, 0x6d3985c698bfce2aL), MetaIdFactory.conceptId(0xf72d32028a4541adL, 0xbb612369f7191040L, 0x8724b429f10bb1bL), MetaIdFactory.conceptId(0xf72d32028a4541adL, 0xbb612369f7191040L, 0x6415fe5db89abbdaL), MetaIdFactory.conceptId(0xf72d32028a4541adL, 0xbb612369f7191040L, 0x6d3985c698bd8892L)).seal();
}
