package B.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class BFalseExpression_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    //  
    //  
    String returnValueAuxVar_3;
    //  
    do {
      returnValueAuxVar_3 = SConceptOperations.conceptAlias(SNodeOperations.getConcept(ctx.getPrimaryInput()));
      break;
    } while (false);
    //  
    tgs.append(returnValueAuxVar_3);
    //  
  }
}
