package Solidity.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class FunctionCall_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.functionName$$rXG));
    tgs.append(" ");
    tgs.append("(");
    tgs.append(" ");
    for (SNode elem_23 : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.inputParameterList$$srI))) {
      tgs.appendNode(elem_23);
      if ((SNodeOperations.getNextSibling(elem_23) != null)) {
        tgs.append(" ");
      }
    }
    tgs.append(" ");
    tgs.append(")");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink functionName$$rXG = MetaAdapterFactory.getContainmentLink(0xf72d32028a4541adL, 0xbb612369f7191040L, 0x6d3985c6995cf507L, 0x6d3985c6995cf508L, "functionName");
    /*package*/ static final SContainmentLink inputParameterList$$srI = MetaAdapterFactory.getContainmentLink(0xf72d32028a4541adL, 0xbb612369f7191040L, 0x6d3985c6995cf507L, 0x6d3985c6995cf50aL, "inputParameterList");
  }
}
