package Solidity.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ReturnStatement_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("return");
    tgs.append(" ");
    if (ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.returns$8Y2n)).count() > 1) {
      tgs.append("(");
    }
    for (SNode ret : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.returns$8Y2n))) {
      tgs.appendNode(ret);
      if ((SNodeOperations.getNextSibling(ret) != null)) {
        tgs.append(",");
        tgs.append(" ");
      }
    }
    if (ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.returns$8Y2n)).count() > 1) {
      tgs.append(")");
    }
    tgs.append(";");

  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink returns$8Y2n = MetaAdapterFactory.getContainmentLink(0xf72d32028a4541adL, 0xbb612369f7191040L, 0x6d3985c698be402fL, 0x6d3985c698be4030L, "returns");
  }
}
